app/admin/views.py
#！/usr/bin/env python
#! -*-coding:utf-8 -*-
#!@Author : zhuxx
#!@time : 2020/05/08 09:56

from flask import Blueprint, render_template, request, session, redirect, url_for, jsonify, send_from_directory
from flask_sqlalchemy import get_debug_queries
from werkzeug.utils import secure_filename

from app.models import User,Role,AdminLog,TaskReport,Tasks,Env,TaskResult,Auth,TaskRun
from app.admin.util import get_welcome_info,line_base,add_example,common_del,edit_example,search_info,task_run,\
    upload_task,cpu_line,memory_liquid,net_io_line,disk_line,add_common,word_could,add_running
from app.admin.forms import AddTask,AuthForm,RoleForm,UserForm,TaskRunning
from setting import BasicConfig
from exts import db

from datetime import datetime
from functools import wraps
from itertools import product
import os
import logging

admin = Blueprint('admin',__name__)
line_info = []

# 有无访问权限装饰器： 判断用户权限控制
def admin_auth(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        user_id = session['user_id']
        admin = User.query.join(Role).filter(Role.id == User.role_id,
                                             User.user_id == user_id).first()
        auths = admin.role.auths
        auth_list = [int(i) for i in auths.split(',')]
        auth_all = Auth.query.all()
        real_auth = []
        for auth,val in product(auth_all,auth_list):
            if auth.id == val:
                real_auth.append(auth.url)
        rule = str(request.url_rule)
        if rule not in real_auth:
            return render_template('error/404.html',info='您无权访问/操作此内容，请联系管理员开启此权限')
        return func(*args, **kwargs)
    return wrapper

#首页
@admin.route('/index')
def index():
    session_id = session['user_id']
    users = User.query.filter_by(user_id=session_id).first()
    username = users.username
    return render_template('index.html',username=username)

#个人信息
@admin.route('/profile')
def profile():
    session_id = session['user_id']
    users = User.query.filter_by(user_id=session_id).first()
    return render_template('profile.html',user=users)

#修改密码
@admin.route('/editpwd',methods=['GET','POST'])
def editpwd():
    user_id = session['user_id']
    user = User.query.filter_by(user_id=user_id).first()
    if request.method == 'GET':
        return render_template('edit_pwd.html',user=user)
    else:
        oldpwd = request.form.get('oldpwd')
        newpwd1 = request.form.get('newpwd1')
        newpwd2 = request.form.get('newpwd2')
        print(oldpwd)
        user.password = newpwd1
        db.session.commit()
        return render_template('edit_pwd.html', user=user,message="密码修改成功！")

#校验密码
@admin.route('/checkpwd')
def checkpwd():
    oldpwd = request.args.get('oldpwd', '')
    user_id = session['user_id']
    user = User.query.filter_by(user_id=user_id).first()
    if user.check_password(oldpwd):
        data = {
            "name": user.email,
            "status": 11
        }
    else:
        data = {
            "name": None,
            "status": 00
        }
    return jsonify(data)

#欢迎页面
@admin.route('/welcome')
def welcome():
    global line_info
    session_id = session['user_id']
    users = User.query.filter_by(user_id=session_id).first()
    username = users.username
    admin_logs = AdminLog.query.filter_by(admin_id=session_id).order_by(AdminLog.time.desc())
    login_count = admin_logs.count() // 2 + 1
    if admin_logs.first():
        login_ip_now = admin_logs.first().ip
        login_ip_time = admin_logs.first().time
    else:
        login_ip_now = '127.0.0.1'
        login_ip_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    infos,line_info = get_welcome_info(User,Tasks,TaskReport)
    return render_template('welcome.html',username=username,login_count=login_count,login_ip_now=login_ip_now,
                           login_ip_time=login_ip_time,infos=infos)

#通过Ajax获取line数据
@admin.route('/line')
def get_line_chart():
    c = line_base(*line_info)
    line_info.clear()
    return c.dump_options_with_quotes()

###################
#    用例展示     #
##################

#用例展示
@admin.route('/list_show')
@admin_auth
def list_show():
    pages = int(request.args.get('page',1))
    paginate = Tasks.query.paginate(pages,10)
    tasks = paginate.items
    return render_template('list_show.html',tasks=tasks,paginate=paginate)

#添加用例
@admin.route('/list_add',methods=['GET','POST'])
@admin_auth
def list_add():
    if request.method == "GET":
        return render_template('list_add.html')
    else:
        forms = AddTask(request.form)
        if forms.validate():
            datas = forms.data
            data = add_example(Tasks, datas, db)
        else:
            data = {
                "msg": "表单验证失败",
                "status": "202"
            }
        return jsonify(data)

#编辑用例
@admin.route('/list_edit/',methods=['GET','POST'])
@admin_auth
def list_edit():
    if request.method == "GET":
        ids = request.args.get('id','')
        print(ids)
        if ids or ids != "":
            tasks = Tasks.query.filter(Tasks.id==int(ids)).first()
            return render_template('list_edit.html',data=tasks)
        else:
            tasks = Tasks.query.filter(Tasks.id == 1).first()
            return render_template('list_edit.html', data=tasks)
    else:
        forms = AddTask(request.form)
        if forms.validate():
            datas = forms.data
            data = edit_example(Tasks,datas,db)
        else:
            data = {
                "msg": "表单验证失败",
                "status": "202"
            }
        return jsonify(data)

#删除单个用例
@admin.route('/list_single_del',methods=['POST'])
@admin_auth
def list_single_del():
    if request.method == "POST":
        ids = request.values.get('id')
        data = common_del(Tasks,ids,db)
        return jsonify(data)


#批量删除用例
@admin.route('/list_all_del',methods=['POST'])
@admin_auth
def list_all_del():
    if request.method == "POST":
        ids = request.values.get('id')
        data = common_del(Tasks, ids, db)
        return jsonify(data)

#用例执行
@admin.route('/running_tasks',methods=['POST'])
@admin_auth
def running_task():
    if request.method == "POST":
        ids = request.values.get('id')
        data = task_run(Tasks,TaskResult,TaskReport,Env,ids,db)
        return jsonify(data)
    else:
        return {'msg':'出现问题了！','status':1002}


#用例搜索
@admin.route('/list_search',methods=['GET','POST'])
def list_search():
    if request.method == "GET":
        key = request.args.get('key')
        pages = int(request.args.get('page', 1))
        sql = Tasks.task_id.like('%{}%'.format(key)) | Tasks.task_name.like('%{}%'.format(key))
        # sql = (Tasks.task_id == key)
        paginate = search_info(Tasks,sql,pages,db)
        tasks = paginate.items
        return render_template('list_show.html',paginate=paginate,tasks=tasks)

#报告展示首页
@admin.route('/list_show_report_index')
@admin_auth
def list_show_report_index():
    pages = int(request.args.get('page', 1))
    paginate = TaskReport.query.paginate(pages, 10)
    report = paginate.items
    return render_template('list_show_report.html', reports=report, paginate=paginate)

#报告展示
@admin.route('/list_show_report',methods=['GET'])
@admin_auth
def list_show_report():
    name = request.args.get('name',"")
    print(name)
    return render_template('report/{}.html'.format(name))


#报告搜索
@admin.route('/list_search_report',methods=['GET','POST'])
def list_search_report():
    if request.method == "GET":
        key = request.args.get('key')
        pages = int(request.args.get('page', 1))
        sql = TaskReport.report_name.like('%{}%'.format(key))
        paginate = search_info(TaskReport,sql,pages,db)
        reports = paginate.items
        return render_template('list_show_report.html',paginate=paginate,reports=reports)

#下载
@admin.route('/download/<filename>')
def download(filename):
    if filename == 'demo.xlsx':
        real_path = BasicConfig.BASIC_PATH + "/uploade_data/"
        real_filename = filename
    else:
        real_path = BasicConfig.BASIC_PATH + "/app/templates/report"
        real_filename = "{filename}.html".format(filename=filename)
        print(real_path,real_filename)
    return send_from_directory(real_path,real_filename,mimetype='application/octet-stream')

#上传
@admin.route('/upload',methods=['GET','POST'])
def upload():
    size = BasicConfig.MAX_CONTENT_LENGTH / 1024 ** 3
    allow = BasicConfig.ALLOWED_EXTENSIONS
    if request.method == 'GET':
        return render_template('upload.html',msg='请选择上传文件',size=size,info=allow)
    else:
        f = request.files['file']
        suffix = f.filename.split('.')[-1]
        if suffix in BasicConfig.ALLOWED_EXTENSIONS:
            filename = secure_filename(f.filename)
            file_path = os.path.join(BasicConfig.UPLOAD_FOLDER,filename)
            print(file_path)
            f.save(file_path)
            upload_task(db,Tasks,file_path)
            return redirect(url_for('admin.list_show'))
        else:
            return render_template('upload.html',msg='上传出现问题',size=size,info=allow)

#测试结果展示
@admin.route('/list_show_result')
@admin_auth
def list_show_result():
    pages = int(request.args.get('page', 1))
    paginate = TaskResult.query.paginate(pages, 10)
    tasks = paginate.items
    return render_template('list_show_result.html', tasks=tasks, paginate=paginate)

#测试结果搜索
@admin.route('/list_result_search',methods=['GET'])
def list_result_search():
    if request.method == "GET":
        key = request.args.get('key')
        pages = int(request.args.get('page', 1))
        sql = TaskResult.task_id.like('%{}%'.format(key)) | TaskResult.task_son_id.like('%{}%'.format(key))
        paginate = search_info(TaskResult, sql, pages, db)
        tasks = paginate.items
        return render_template('list_show_result.html', paginate=paginate, tasks=tasks)

#用例模板展示
@admin.route('/list_task_model')
def list_task_model():
    pages = int(request.args.get('page', 1))
    paginate = Tasks.query.paginate(pages, 1)

app/login/__init__.py
#！/usr/bin/env python
#! -*-coding:utf-8 -*-
#!@Author : zhuxx
#!@time : 2020/05/06 19:07

from .views import Login

app/login/views.py
#！/usr/bin/env python
#! -*-coding:utf-8 -*-
#!@Author : zhuxx
#!@time : 2020/05/06 19:07

from flask import Blueprint, render_template, request, session, redirect, url_for, jsonify

from app.models import User,AdminLog
from exts import db

import datetime


Login = Blueprint('login',__name__)

@Login.route('/')
def index():
    return redirect(url_for('login.login'))

@Login.route('/login',methods=['GET','POST'])
def login():
    if request.method == "GET":
        return render_template('login.html')
    else:
        user = request.form.get('user')
        pwd = request.form.get('pwd')
        username = User.query.filter_by(username=user).first()
        if user and pwd:
            if username:
                session['user_id'] = username.user_id
                if username.check_password(pwd):
                    op_log = AdminLog(
                        admin_id=username.user_id,
                        ip=request.remote_addr,
                        time=datetime.datetime.now(),
                        operate="用户：{} 进行了登录操作！".format(username.username)
                    )
                    db.session.add(op_log)
                    db.session.commit()
                    return jsonify({'code':200,'error':""})
                else:
                    print('用户名或密码错误')
                    return jsonify({'code':401,'error':'用户名或密码错误'})
            else:
                return jsonify({'code':401,'error':'用户名或密码错误'})
        else:
            return jsonify({'code': 401, 'error': '用户名或密码不能为空'})

@Login.route('/logout')
def logout():
    users = User.query.filter(User.user_id==session['user_id']).first()
    op_log = AdminLog(
        admin_id=users.user_id,
        ip=request.remote_addr,
        time=datetime.datetime.now(),
        operate="用户：{} 进行了注销操作！".format(users.username)
    )
    db.session.add(op_log)
    db.session.commit()
    del session['user_id']
    return redirect(url_for('login.login'))

app/templates/edit_pwd_details.html
 <script>
 $(function() {
                var checkok1=false;
                var checkok2=false;
                var checkok3=false;
 //验证旧密码
     $("input[name='oldpwd']").blur(function () {
             var pwd=$("input[name='oldpwd']").val();
             var dd = {'oldpwd':pwd};
               $.ajax({
             type: "GET",
             url: "{{ url_for('admin.checkpwd') }}",
             dataType: "json",
             data: dd,
             success: function(json) {
                 if(json.status==11){
                      $("#oldpwd").next().text('密码正确').removeClass('state1').addClass('state3');
                      checkok1=1;
                 }
                 else {
                      $("#oldpwd").next().text('密码不对').removeClass('state1').addClass('state4');
                 }
             },

         });
     });
	 //验证新密码
          $('input[name="newpwd1"]').focus(function(){
                    $("#newpwd1").next().text('密码应该为6-15位之间').removeClass('state1').addClass('state2');
                }).blur(function(){
                    if($("#newpwd1").val().length >= 6 && $(this).val().length <=15 && $(this).val()!=''){
                        $("#newpwd1").next().text('输入有效').removeClass('state1').addClass('state4');
                        checkok2=true;
                    }else{
                        $("#newpwd1").next().text('密码应该为6-20位之间').removeClass('state1').addClass('state3');
                    }
                     
                });
	   //再次验证新密码
                    $('input[name="newpwd2"]').focus(function(){
                    $(this).next().text('两次输入密码需要一样').removeClass('state1').addClass('state2');
                }).blur(function(){
                    if($(this).val().length >= 6 && $(this).val().length <=15 && $(this).val()!='' && $(this).val() == $('input[name="newpwd2"]').val()){
                        $(this).next().text('输入成功').removeClass('state1').addClass('state4');
                        checkok3=true;
                    }else{
                        $(this).next().text('您输入的两次密码不一样哦').removeClass('state1').addClass('state3');
                    }

                });
          //提交按钮,所有验证通过方可提交
                 $('#button_1').click(function(){
            if(checkok1 && checkok2 && checkok3){
                        $('form').submit();
                    }else{
                        return false;
                    }
        });
 })

 </script>
<div class="container">
    <div class="form_div">
      <form action="{{ url_for('admin.editpwd') }}" class="form-signin" role="form" method='post'>
        <h2 class="form-signin-heading">修改密码</h2>
        <input type="password" class="form-control" placeholder="请输入旧密码" required autofocus name="oldpwd" id="oldpwd">
          <span class='state1'>请输入旧密码</span>
            <div style="height:10px;clear:both;display:block"></div>
        <input type="password" class="form-control" placeholder="请输入新密码" required name="newpwd1" id="newpwd1">
		 <span class='state1'>请输入新密码</span>
          <div style="height:10px;clear:both;display:block"></div>
       <input type="password" class="form-control" placeholder="请再次输入新密码" required name="newpwd2" id="newpwd2">
	    <span class='state1'>请再次输入新密码</span>
            <div style="height:10px;clear:both;display:block"></div>
        <div class="form-group">
                <button type="button" class="btn btn-primary" id="button_1">提交修改</button>
            </div>
          <div style="height:10px;clear:both;display:block"></div>
      </form>
        {% if  message %}
            <p style="color:red">{{ message }} </p>
        {% endif %}
        </div>
    </div>

app/templates/image_compare.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/list_add.html
{% include "common_header.html" %}
<title>{% block title %}添加用例{% endblock %}</title>
{% block header %}{% endblock %}

<body>
{% block head %}{% endblock %}

<h1>{% block page_title %}添加用例{% endblock %}</h1>

{% block main_content %}

<article class="page-container">
	<div class="form form-horizontal" id="form-admin-add" >

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>用例编号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="用例编号" id="task_id" name="task_id"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>用例子编号：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="用例子编号" id="task_son_id" name="task_son_id"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>用例名称：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="用例名称" id="task_name" name="task_name"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>用例描述：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="用例描述" id="task_description" name="task_description"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>method：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="task_method" id="task_method" name="task_method"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>url：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="url" id="task_url" name="task_url"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>请求数据：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" value="" placeholder="" id="task_data" name="task_data"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>预期结果：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" autocomplete="off" value="" placeholder="权限地址" id="task_result" name="task_result"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>session信息：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" autocomplete="off"  value="0" placeholder="session信息" id="task_session" name="task_result"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>accessToken：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" autocomplete="off"  value="0" placeholder="accessToken" id="session" name="session"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>session作者：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" autocomplete="off"  placeholder="session作者" id="task_auth" name="task_auth"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>环境信息：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" class="input-text" autocomplete="off" value="0" placeholder="环境信息" id="task_env" name="task_result"/>
            </div>
        </div>

        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-3"><span class="c-red"></span>录入时间：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <input type="text" onfocus="WdatePicker({ maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%m-%d %H:%M:%S\'}' })" id="task_time" class="input-text Wdate" style="width:120px;">
            </div>
        </div>

        <div class="row cl">
            <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
                <button id="submit" neme="submit" class="btn btn-primary radius" onclick="danji()" type="submit">提交</button>
            </div>
        </div>
	</div>
</article>


{% endblock %}
{% include "common_footer.html" %}
{% block footr_css_js %}

<!--_footer 作为公共模版分离出去-->

<script src="{{ url_for('static',filename='js/jquery/1.9.1/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/layer/2.4/layer.js') }}"></script>
<script src="{{ url_for('static',filename='js/h-ui/js/H-ui.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/h-ui.admin/js/H-ui.admin.js') }}"></script>
<!--/_footer 作为公共模版分离出去-->
<!--请在下方写此页面业务相关的脚本-->
<script src="{{ url_for('static',filename='js/My97DatePicker/4.8/WdatePicker.js') }}"></script>
<script src="{{ url_for('static',filename='js/datatables/1.10.0/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/laypage/1.2/laypage.js') }}"></script>

<script type="text/javascript">
    /*从cookie中获取csrf_token*/
    function danji(){
        var task_id = $("#task_id").val();
        var task_son_id = $("#task_son_id").val();
        var task_name = $("#task_name").val();
        var task_description = $("#task_description").val();
        var task_method = $("#task_method").val();
        var task_url = $("#task_url").val();
        var task_data = $("#task_data").val();
        var task_result = $("#task_result").val();
        var task_session = $("#task_session").val();
        var task_auth = $("#task_auth").val();
        var task_env = $("#task_env").val();
        var task_time = $("#task_time").val();
        var session = $("#session").val();

        $.ajax({
            type: 'POST',
            url: "{{ url_for('admin.list_add') }}",
            // headers: {"X-CSRFToken": getCookie("csrf_token")},
            data : {
                task_id : task_id,
                task_son_id:task_son_id,
                task_name:task_name,
                task_description:task_description,
                task_method:task_method,
                task_url : task_url,
                task_data: task_data,
                task_result:task_result,
                task_session:task_session,
                task_auth:task_auth,
                task_env:task_env,
                task_time:task_time,
                session:session
            },
            success: function(data){
                if(data.status==200){
                layer.msg('已添加成功!',{icon:1,time:2000});
                var index = parent.layer.getFrameIndex(window.name);//关闭窗口
                setTimeout("parent.layer.closeAll()",1000);  // parent.layer.closeAll()方法有效
                }
                else {
                    layer.msg(data.msg)
                }
            },
            error:function(data) {
                console.log(data.msg);
            },
        });
    }
</script>
{% endblock %}

app/templates/logs_login.html
{% include "common_header.html" %}
<title>{% block title %}登录日志展示{% endblock %}</title>
{% block header %}{% endblock %}


<html>
<body>


{% block main_content %}
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页
    <span class="c-gray en">&gt;</span> 系统管理
    <span class="c-gray en">&gt;</span> 登录日志展示
    <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" >
        <i class="Hui-iconfont">&#xe68f;</i>
    </a>
</nav>


<div class="page-container">
	<div class="text-c">
		<div class="Huiform">
			<input type="text" class="input-text" style="width:250px" placeholder="搜索用户名" id="search_key" name="search_key">
			<button type="submit" class="btn btn-success" id="do_search" name="do_search" >
                <i class="Hui-iconfont">&#xe665;</i> 搜索用户名
            </button>
		</div>
	</div>
	<div class="cl pd-5 bg-1 bk-gray mt-20">
        <span class="r">共有数据：<strong>{{ paginate.total }}</strong> 条</span>
    </div>
	<table class="table table-border table-bordered table-bg">
		<thead>
			<tr>
				<th scope="col" colspan="12">登录日志展示</th>
			</tr>
			<tr class="text-c">
				<th>描述</th>
				<th>登录IP</th>
                <th>登陆时间</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
		    {% for log in logs %}
			<tr class="text-c">
				<td>{{log.operate}}</td>
				<td>{{log.ip}}</td>
				<td>{{log.time}}</td>
				<td>
                    <a title="删除" href="javascript:;" onclick="admin_permission_del(this,id='{{log.id}}')" class="ml-5" style="text-decoration:none">
                        <i class="Hui-iconfont">&#xe6e2;</i>
                    </a>
                </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<!--_分页开始-->
    <div class="dataTables_wrapper">
	    <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">共{{paginate.pages}}页 </div>

        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">

            <a class="paginate_button previous disabled" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" href='{{ url_for("admin.logs_login") }}?page=1' >首页</a>
            <!--_如果有上一页-->
            {% if paginate.has_prev %}
            <a class="paginate_button previous disabled" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" href='{{ url_for("admin.logs_login") }}?page={{ paginate.prev_num }}' >上一页</a>
            {% else %}
            <a class="paginate_button previous disabled" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" href="#" >上一页</a>
            {% endif %}

            <span>
                <a class="paginate_button current" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0">{{paginate.page}}</a>
            </span>

            {% if paginate.has_next %}
		    <a class="paginate_button next disabled" aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0"  href='{{ url_for("admin.logs_login") }}?page={{ paginate.next_num }}'>下一页</a>

		    {% else %}

		    <a class="paginate_button next disabled" aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0"  href="#">下一页</a>

            {% endif %}

		    <a class="paginate_button next disabled" aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0"  href='{{ url_for("admin.logs_login") }}?page={{ paginate.pages }}'>尾页</a>

		</div>

	<!--_分页结束-->
    </div>
</div>


{% endblock %}
{% include "common_footer.html" %}
{% block footr_css_js %}

<!--请在下方写此页面业务相关的脚本-->

<script src="{{ url_for('static',filename='js/datatables/1.10.0/jquery.dataTables.min.js') }}"></script>

<script type="text/javascript">
    /*搜索*/
    $(document).ready(function () {
        $("#do_search").click(function(){
         var key=$("#search_key").val();
           location.href="{{url_for('admin.logs_login_search')}}?page={{paginate.page}}&key=" +key;
        });
    });
</script>

<script type="text/javascript">

    /*管理员-权限-删除*/
    function admin_permission_del(obj,id){
        layer.confirm('确认要删除吗？',function(index){
            $.ajax({
                type: 'POST',
                url: "{{ url_for('admin.list_single_del') }}",
                dataType: 'json',
                data : {　　　　　　　　　　　
    　　　　　　　　id :id,                             　
    　　　　　　},
                success: function(data){
                    $(obj).parents("tr").remove();
                    layer.msg('已删除!',{icon:1,time:1000});
                },
                error:function(data) {
                    console.log(data.msg);
                },
            });
        });
    }

</script>

{% endblock %}
</body>
</html>

app/templates/logs_sql.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/profile_details.html
<div class="page-container">
	<p class="f-20 text-success"> 个人信息</p>
	<table class="table table-border table-bordered table-bg mt-20">
		<tbody>
			<tr>
				<th width="30%">姓名</th>
				<td><span id="lbServerName">{{ user.username }}</span></td>
			</tr>
			<tr>
				<td>邮箱</td>
				<td>{{ user.email }}</td>
			</tr>
			<tr>
				<td>注册时间</td>
				<td>{{ user.reg_time }}</td>
			</tr>
		</tbody>
	</table>
</div>